version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER: 'root'
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src


  mysql_db:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie
    ports:
      - "6033:3307"
    volumes:
      - ./data-db:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 8081:80
    depends_on:
     - mysql_db
    volumes:
      - /sessions

  movie_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-api-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mysql_db
    volumes:
      - ./src:/movie_app/src