version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movies
    ports:
      - '3308:3308' # Mapping host port 3308 to container port 3306
    volumes:
      - ./data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '8080:80'
    depends_on:
      - db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-api
    ports:
      - '3000:3000'
    depends_on:
      - db
      - phpmyadmin
    environment:
      - TYPEORM_HOST=db
    volumes:
      - ./src:/app/src
