version: '3.9'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie
    ports:
      - "6033:3306"
    volumes:
      - ./data-db:/var/lib/mysql
    expose:
      - "3306"
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
     - mysql_db
    volumes:
      - /sessions

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-api-app
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - mysql_db
    volumes:
      - ./src:/app/src